/**
 * Multilingual city descriptions for the city detail page.
 * Short, factual profiles focused on economy, cost, and key characteristics.
 * Structure: Record<cityId, Record<locale, description>>
 */

export const CITY_INTROS: Record<number, Record<string, string>> = {
  1: {
    zh: "美国金融和商业中心，高薪职位集中。生活成本极高，尤其是住房费用。全球经济影响力最大的城市之一。",
    en: "America's financial and business hub with concentrated high-paying jobs. Extremely high cost of living, especially housing. One of the most economically influential cities in the world.",
    ja: "アメリカの金融・ビジネスの中心地で、高収入の仕事が集中。生活費は極めて高く、特に住居費が突出。世界で最も経済的影響力のある都市の一つ。",
    es: "Centro financiero y comercial de EE.UU., con alta concentración de empleos bien remunerados. Costo de vida extremadamente alto, especialmente en vivienda. Una de las ciudades con mayor influencia económica global.",
  },
  2: {
    zh: "欧洲金融枢纽，薪资水平较高。生活成本尤其是住房昂贵，但低于纽约。文化和教育资源丰富。",
    en: "European financial hub with relatively high salaries. High cost of living, especially housing, though lower than New York. Rich cultural and educational resources.",
    ja: "ヨーロッパの金融ハブで、給与水準は比較的高い。生活費、特に住居費は高いがニューヨークよりは低い。文化・教育資源が豊富。",
    es: "Centro financiero europeo con salarios relativamente altos. Alto costo de vida, especialmente en vivienda, aunque menor que Nueva York. Ricos recursos culturales y educativos.",
  },
  3: {
    zh: "亚洲经济引擎，薪资竞争力强。生活成本相对欧美城市较低。公共交通发达，生活便利度高。",
    en: "Asia's economic engine with competitive salaries. Cost of living is relatively lower than Western cities. Excellent public transit and high daily convenience.",
    ja: "アジアの経済エンジンで、給与の競争力が高い。生活費は欧米都市と比べて相対的に低い。公共交通が発達し、生活利便性が高い。",
    es: "Motor económico de Asia con salarios competitivos. Costo de vida relativamente bajo comparado con ciudades occidentales. Transporte público desarrollado y alta comodidad de vida.",
  },
  4: {
    zh: "中国政治经济中心，增长潜力大。生活成本相对低廉，但房价上涨迅速。国际化机会众多。",
    en: "China's political and economic center with strong growth potential. Cost of living is relatively low, though housing prices are rising fast. Abundant international opportunities.",
    ja: "中国の政治経済の中心で、成長ポテンシャルが大きい。生活費は比較的低いが、住宅価格は急上昇中。国際的な機会が豊富。",
    es: "Centro político y económico de China con gran potencial de crecimiento. Costo de vida relativamente bajo, aunque los precios de vivienda suben rápidamente. Numerosas oportunidades internacionales.",
  },
  5: {
    zh: "中国最大的经济体和金融中心，国际贸易枢纽。生活成本仅次于北京，但薪资水平最高。创新和创业机会丰富。",
    en: "China's largest economy and financial center, an international trade hub. Cost of living is second only to Beijing, but salaries are the highest. Rich innovation and entrepreneurship opportunities.",
    ja: "中国最大の経済・金融センターで、国際貿易のハブ。生活費は北京に次ぐが、給与水準は最高。イノベーションと起業の機会が豊富。",
    es: "La mayor economía y centro financiero de China, hub del comercio internacional. Costo de vida solo superado por Pekín, pero con los salarios más altos. Abundantes oportunidades de innovación y emprendimiento.",
  },
  6: {
    zh: "澳大利亚经济中心，薪资水平在发达国家中领先。生活成本较高但生活质量优秀。宜居指数世界领先。",
    en: "Australia's economic center with salaries leading among developed nations. High cost of living but excellent quality of life. World-leading livability index.",
    ja: "オーストラリアの経済中心地で、先進国の中でも給与水準が高い。生活費は高いが生活の質は優秀。世界トップクラスの住みやすさ指数。",
    es: "Centro económico de Australia con salarios líderes entre países desarrollados. Alto costo de vida pero excelente calidad de vida. Índice de habitabilidad líder mundial.",
  },
  7: {
    zh: "亚太金融中心，薪资水平在亚洲最高。税收优惠吸引国际人才。清洁高效的城市环境和完善的系统。",
    en: "Asia-Pacific financial center with the highest salaries in Asia. Tax incentives attract international talent. Clean, efficient urban environment with well-developed systems.",
    ja: "アジア太平洋の金融センターで、アジア最高の給与水準。税制優遇が国際人材を惹きつける。清潔で効率的な都市環境と整備されたシステム。",
    es: "Centro financiero de Asia-Pacífico con los salarios más altos de Asia. Incentivos fiscales que atraen talento internacional. Entorno urbano limpio y eficiente con sistemas bien desarrollados.",
  },
  8: {
    zh: "欧洲主要文化和艺术中心，薪资中等。生活成本适中，美食和文化享受丰富。生活节奏相对悠闲。",
    en: "Major European cultural and arts center with moderate salaries. Moderate cost of living, rich gastronomy and cultural offerings. Relatively relaxed pace of life.",
    ja: "ヨーロッパの主要な文化・芸術の中心地で、給与は中程度。生活費は適度で、美食と文化が充実。生活のペースは比較的ゆったり。",
    es: "Gran centro cultural y artístico europeo con salarios moderados. Costo de vida moderado, rica gastronomía y oferta cultural. Ritmo de vida relativamente relajado.",
  },
  9: {
    zh: "加拿大最大城市，薪资和生活成本均衡。多元化城市，移民友好政策。交通便利，教育医疗资源优质。",
    en: "Canada's largest city with balanced salaries and cost of living. Diverse city with immigrant-friendly policies. Convenient transit and quality education and healthcare.",
    ja: "カナダ最大の都市で、給与と生活費のバランスが良い。多文化都市で移民に優しい政策。交通が便利で、教育・医療の質が高い。",
    es: "La ciudad más grande de Canadá con equilibrio entre salarios y costo de vida. Ciudad diversa con políticas favorables a la inmigración. Transporte conveniente y recursos educativos y sanitarios de calidad.",
  },
  10: {
    zh: "亚洲金融中心，薪资竞争力强。生活成本高，尤其房价全球屈指可数。国际化程度亚洲最高。",
    en: "Asian financial center with competitive salaries. High cost of living, with housing prices among the world's highest. The most internationalized city in Asia.",
    ja: "アジアの金融センターで、給与の競争力が高い。生活費が高く、特に住宅価格は世界屈指。アジアで最も国際化された都市。",
    es: "Centro financiero asiático con salarios competitivos. Alto costo de vida, con precios de vivienda entre los más altos del mundo. La ciudad más internacionalizada de Asia.",
  },
  11: {
    zh: "美国娱乐和科技中心，薪资水平高。生活成本高但低于纽约。气候宜人，创意产业汇聚。",
    en: "America's entertainment and tech center with high salaries. High cost of living but lower than New York. Pleasant climate and a hub for creative industries.",
    ja: "アメリカのエンタメ・テック中心地で、給与水準が高い。生活費は高いがニューヨークより低い。気候が良く、クリエイティブ産業が集積。",
    es: "Centro de entretenimiento y tecnología de EE.UU. con altos salarios. Alto costo de vida pero menor que Nueva York. Clima agradable y polo de industrias creativas.",
  },
  12: {
    zh: "硅谷所在地，科技行业薪资最高。生活成本全美最高，房价和租金昂贵。创新创业氛围浓厚。",
    en: "Home of Silicon Valley with the highest tech salaries. Highest cost of living in the U.S., with expensive housing and rent. Strong culture of innovation and entrepreneurship.",
    ja: "シリコンバレーの所在地で、テック業界の給与は最高水準。生活費は全米最高で、住宅価格と家賃が高額。イノベーションと起業の雰囲気が濃厚。",
    es: "Sede de Silicon Valley con los salarios tecnológicos más altos. El costo de vida más alto de EE.UU., con vivienda y alquiler caros. Fuerte cultura de innovación y emprendimiento.",
  },
  13: {
    zh: "美国中西部金融中心，薪资中等偏高。生活成本相对美国大城市较低。文化机构和金融企业众多。",
    en: "Midwestern U.S. financial center with moderately high salaries. Cost of living is relatively low among major U.S. cities. Numerous cultural institutions and financial firms.",
    ja: "アメリカ中西部の金融センターで、給与は中〜高水準。生活費はアメリカの大都市の中では比較的低い。文化施設や金融企業が多数。",
    es: "Centro financiero del medio oeste de EE.UU. con salarios moderadamente altos. Costo de vida relativamente bajo entre las grandes ciudades estadounidenses. Numerosas instituciones culturales y empresas financieras.",
  },
  14: {
    zh: "中东商业枢纽，税收优势吸引国际人才。现代化基础设施完善。消费成本相对中等偏低。",
    en: "Middle Eastern business hub with tax advantages attracting international talent. Well-developed modern infrastructure. Relatively moderate consumer costs.",
    ja: "中東のビジネスハブで、税制優遇が国際人材を惹きつける。近代的なインフラが充実。消費コストは比較的中程度。",
    es: "Centro comercial de Oriente Medio con ventajas fiscales que atraen talento internacional. Infraestructura moderna bien desarrollada. Costos de consumo relativamente moderados.",
  },
  15: {
    zh: "欧洲商业和航运中心，薪资竞争力强。生活成本中等，自行车文化特色。国际企业总部众多。",
    en: "European business and shipping center with competitive salaries. Moderate cost of living and distinctive cycling culture. Home to many international corporate headquarters.",
    ja: "ヨーロッパのビジネス・海運の中心地で、給与の競争力が高い。生活費は中程度で、自転車文化が特徴的。国際企業の本社が多数。",
    es: "Centro comercial y naviero europeo con salarios competitivos. Costo de vida moderado y distintiva cultura ciclista. Sede de numerosas empresas internacionales.",
  },
  16: {
    zh: "瑞士金融中心，薪资全球最高。生活成本最高，物价高企。稳定的政治和经济环境。",
    en: "Swiss financial center with the world's highest salaries. Highest cost of living with elevated prices. Stable political and economic environment.",
    ja: "スイスの金融センターで、給与は世界最高水準。生活費は最高クラスで物価が高い。安定した政治・経済環境。",
    es: "Centro financiero suizo con los salarios más altos del mundo. Costo de vida máximo con precios elevados. Entorno político y económico estable.",
  },
  17: {
    zh: "国际组织总部云集，薪资水平很高。生活成本仅次于苏黎世。国际化程度最高。",
    en: "Hub of international organizations with very high salaries. Cost of living second only to Zurich. The highest degree of internationalization.",
    ja: "国際機関が集積し、給与水準が非常に高い。生活費はチューリッヒに次ぐ。国際化の度合いが最も高い。",
    es: "Sede de numerosas organizaciones internacionales con salarios muy altos. Costo de vida solo superado por Zúrich. El mayor grado de internacionalización.",
  },
  18: {
    zh: "德国经济强市，薪资水平高。生活成本相对低，性价比较好。啤酒文化和品质生活闻名。",
    en: "Germany's economic powerhouse with high salaries. Relatively low cost of living with good value. Known for beer culture and quality of life.",
    ja: "ドイツの経済強都市で、給与水準が高い。生活費は比較的低く、コスパが良い。ビール文化と高い生活の質で有名。",
    es: "Potencia económica de Alemania con altos salarios. Costo de vida relativamente bajo con buena relación calidad-precio. Famosa por su cultura cervecera y calidad de vida.",
  },
  19: {
    zh: "德国首都和创意中心，薪资相对较低。生活成本极低，性价比最高。创业氛围和文化多样性突出。",
    en: "Germany's capital and creative hub with relatively low salaries. Extremely low cost of living with the best value. Outstanding startup scene and cultural diversity.",
    ja: "ドイツの首都でクリエイティブの中心地、給与は比較的低い。生活費が極めて低く、コスパ最高。スタートアップの雰囲気と文化の多様性が際立つ。",
    es: "Capital de Alemania y centro creativo con salarios relativamente bajos. Costo de vida extremadamente bajo con la mejor relación calidad-precio. Destacado ecosistema emprendedor y diversidad cultural.",
  },
  20: {
    zh: "西班牙第二大城市，薪资中等。生活成本低廉，地中海气候宜人。文化遗产和旅游业发达。",
    en: "Spain's second-largest city with moderate salaries. Low cost of living and pleasant Mediterranean climate. Rich cultural heritage and thriving tourism.",
    ja: "スペイン第二の都市で、給与は中程度。生活費が低く、地中海性気候が快適。文化遺産と観光業が発達。",
    es: "Segunda ciudad más grande de España con salarios moderados. Bajo costo de vida y agradable clima mediterráneo. Rico patrimonio cultural y turismo desarrollado.",
  },
  21: {
    zh: "西班牙首都和经济中心，薪资水平提升中。生活成本低，艺术和文化资源丰富。西班牙最国际化城市。",
    en: "Spain's capital and economic center with rising salaries. Low cost of living, rich arts and cultural resources. Spain's most internationalized city.",
    ja: "スペインの首都で経済の中心、給与水準は上昇中。生活費が低く、芸術・文化資源が豊富。スペインで最も国際化された都市。",
    es: "Capital y centro económico de España con salarios en ascenso. Bajo costo de vida, ricos recursos artísticos y culturales. La ciudad más internacionalizada de España.",
  },
  22: {
    zh: "意大利经济中心和时尚之都，薪资中等。生活成本中等偏低，奢侈品和时尚文化汇聚。",
    en: "Italy's economic center and fashion capital with moderate salaries. Moderately low cost of living, a hub for luxury and fashion culture.",
    ja: "イタリアの経済中心地でファッションの都、給与は中程度。生活費は中〜低程度で、高級ブランドとファッション文化が集積。",
    es: "Centro económico de Italia y capital de la moda con salarios moderados. Costo de vida moderadamente bajo, polo del lujo y la cultura de la moda.",
  },
  23: {
    zh: "意大利首都，薪资水平相对较低。生活成本低廉，历史文化遗产世界顶级。旅游业和服务业为主。",
    en: "Italy's capital with relatively low salaries. Low cost of living and world-class historical and cultural heritage. Economy driven by tourism and services.",
    ja: "イタリアの首都で、給与水準は比較的低い。生活費が低く、歴史文化遺産は世界トップクラス。観光業とサービス業が中心。",
    es: "Capital de Italia con salarios relativamente bajos. Bajo costo de vida y patrimonio histórico-cultural de primer nivel mundial. Economía basada en turismo y servicios.",
  },
  24: {
    zh: "欧盟政治中心，薪资中等偏高。生活成本相对低，国际机构雇主众多。巧克力和啤酒文化著名。",
    en: "EU political center with moderately high salaries. Relatively low cost of living with many international institutional employers. Famous for chocolate and beer culture.",
    ja: "EUの政治の中心で、給与は中〜高水準。生活費は比較的低く、国際機関の雇用主が多い。チョコレートとビール文化で有名。",
    es: "Centro político de la UE con salarios moderadamente altos. Costo de vida relativamente bajo con numerosos empleadores de instituciones internacionales. Famosa por su cultura del chocolate y la cerveza.",
  },
  25: {
    zh: "奥地利首都，薪资水平不错。生活成本低，音乐和文化底蕴深厚。连续多年全球生活质量第一。",
    en: "Austria's capital with solid salaries. Low cost of living, deep musical and cultural heritage. Ranked #1 globally in quality of life for consecutive years.",
    ja: "オーストリアの首都で、給与水準は良好。生活費が低く、音楽と文化の伝統が深い。世界の生活の質ランキングで連続1位。",
    es: "Capital de Austria con buenos salarios. Bajo costo de vida, profunda herencia musical y cultural. Número uno mundial en calidad de vida durante años consecutivos.",
  },
  26: {
    zh: "中欧文化明珠，薪资相对较低。生活成本极低，性价比最优。中世纪建筑和艺术氛围浓郁。",
    en: "Central European cultural gem with relatively low salaries. Extremely low cost of living with the best value. Rich medieval architecture and artistic atmosphere.",
    ja: "中欧の文化の宝石で、給与は比較的低い。生活費が極めて低く、コスパ最優秀。中世建築と芸術的な雰囲気が濃厚。",
    es: "Joya cultural de Europa Central con salarios relativamente bajos. Costo de vida extremadamente bajo con la mejor relación calidad-precio. Rica arquitectura medieval y ambiente artístico.",
  },
  27: {
    zh: "波兰经济增长最快城市，薪资提升快。生活成本极低，新兴科技中心。欧洲创业费用最低。",
    en: "Poland's fastest-growing city with rapidly rising salaries. Extremely low cost of living and an emerging tech hub. Lowest startup costs in Europe.",
    ja: "ポーランドで最も成長が速い都市で、給与上昇も急速。生活費が極めて低く、新興テックハブ。ヨーロッパで起業コストが最も低い。",
    es: "La ciudad de mayor crecimiento en Polonia con salarios en rápido ascenso. Costo de vida extremadamente bajo y centro tecnológico emergente. Los costos de emprendimiento más bajos de Europa.",
  },
  28: {
    zh: "葡萄牙首都，薪资水平较低。生活成本极低，气候宜人。数字游民热门目的地。",
    en: "Portugal's capital with relatively low salaries. Extremely low cost of living and pleasant climate. A popular destination for digital nomads.",
    ja: "ポルトガルの首都で、給与水準は比較的低い。生活費が極めて低く、気候が快適。デジタルノマドに人気の目的地。",
    es: "Capital de Portugal con salarios relativamente bajos. Costo de vida extremadamente bajo y clima agradable. Destino popular para nómadas digitales.",
  },
  29: {
    zh: "希腊首都，薪资水平低。生活成本极低，地中海文明发源地。旅游和文化资源丰富。",
    en: "Greece's capital with low salaries. Extremely low cost of living, birthplace of Mediterranean civilization. Rich tourism and cultural resources.",
    ja: "ギリシャの首都で、給与水準は低い。生活費が極めて低く、地中海文明の発祥地。観光・文化資源が豊富。",
    es: "Capital de Grecia con salarios bajos. Costo de vida extremadamente bajo, cuna de la civilización mediterránea. Ricos recursos turísticos y culturales.",
  },
  30: {
    zh: "跨越欧亚的商业中心，薪资相对较低。生活成本极低，历史文化底蕴深。商业创业机会众多。",
    en: "Transcontinental business center straddling Europe and Asia with relatively low salaries. Extremely low cost of living and deep historical heritage. Abundant business and entrepreneurial opportunities.",
    ja: "欧州とアジアにまたがるビジネスの中心地で、給与は比較的低い。生活費が極めて低く、歴史文化の蓄積が深い。ビジネスと起業の機会が豊富。",
    es: "Centro comercial transcontinental entre Europa y Asia con salarios relativamente bajos. Costo de vida extremadamente bajo y profunda herencia histórica. Abundantes oportunidades comerciales y emprendedoras.",
  },
  31: {
    zh: "墨西哥最大城市，薪资相对较低。生活成本低廉，历史文化遗产丰富。拉美地区经济中心。",
    en: "Mexico's largest city with relatively low salaries. Very affordable cost of living and rich historical heritage. Economic hub of Latin America.",
    ja: "メキシコ最大の都市で、給与水準はやや低め。生活費が安く、歴史的文化遺産が豊富。中南米の経済の中心地。",
    es: "La ciudad más grande de México, con salarios relativamente bajos. Costo de vida económico y rico patrimonio histórico-cultural. Centro económico de América Latina.",
  },
  32: {
    zh: "巴西经济中心，薪资中等。生活成本低，南美洲金融枢纽。文化多样，发展潜力大。",
    en: "Brazil's economic center with moderate salaries. Low cost of living and South America's financial hub. Culturally diverse with strong growth potential.",
    ja: "ブラジルの経済の中心地で、給与は中程度。生活費が安く、南米の金融ハブ。文化が多様で成長ポテンシャルが大きい。",
    es: "Centro económico de Brasil con salarios moderados. Bajo costo de vida y hub financiero de Sudamérica. Culturalmente diverso, con gran potencial de desarrollo.",
  },
  33: {
    zh: "巴西最著名城市，薪资相对较低。生活成本低，自然风景优美。旅游业和文化产业发达。",
    en: "Brazil's most famous city with relatively low salaries. Low cost of living and stunning natural scenery. Thriving tourism and cultural industries.",
    ja: "ブラジルで最も有名な都市で、給与はやや低め。生活費が安く、自然の景観が美しい。観光業と文化産業が盛ん。",
    es: "La ciudad más famosa de Brasil con salarios relativamente bajos. Bajo costo de vida y hermosos paisajes naturales. Turismo e industria cultural desarrollados.",
  },
  34: {
    zh: "美国宜居城市，薪资水平较高。生活成本中等，气候温暖常年如春。金融和旅游业发达。",
    en: "A livable US city with relatively high salaries. Moderate cost of living and warm, spring-like climate year-round. Strong finance and tourism sectors.",
    ja: "住みやすい米国の都市で、給与水準はやや高い。生活費は中程度で、一年中温暖な気候。金融・観光業が盛ん。",
    es: "Ciudad habitable de EE.UU. con salarios relativamente altos. Costo de vida moderado y clima cálido casi todo el año. Finanzas y turismo desarrollados.",
  },
  35: {
    zh: "美国首都，政府和非营利机构雇主众多。薪资水平高，生活成本中等。权力运作中心。",
    en: "US capital with many government and nonprofit employers. High salaries and moderate cost of living. The center of political power.",
    ja: "米国の首都で、政府機関や非営利団体の雇用が豊富。給与水準が高く、生活費は中程度。政治の中枢。",
    es: "Capital de EE.UU. con numerosos empleadores gubernamentales y sin fines de lucro. Salarios altos y costo de vida moderado. Centro del poder político.",
  },
  36: {
    zh: "美国教育和医疗中心，薪资高。生活成本高，顶尖大学和医疗机构集中。历史底蕴深厚。",
    en: "US education and healthcare hub with high salaries. High cost of living, home to top universities and medical institutions. Deep historical roots.",
    ja: "米国の教育・医療の中心地で、給与が高い。生活費は高いが、トップクラスの大学や医療機関が集中。歴史的な風格がある。",
    es: "Centro educativo y médico de EE.UU. con salarios altos. Alto costo de vida, con universidades e instituciones médicas de primer nivel. Rica tradición histórica.",
  },
  37: {
    zh: "科技产业集中地，薪资全美前列。生活成本高，亚马逊等科技巨头总部所在。环境优美。",
    en: "Tech industry hub with salaries among the highest in the US. High cost of living, home to Amazon and other tech giants. Beautiful natural surroundings.",
    ja: "テック産業の集積地で、全米トップクラスの給与水準。生活費は高いが、Amazonなどの大手テック企業の本社が所在。自然環境が美しい。",
    es: "Concentración de la industria tecnológica con salarios entre los más altos de EE.UU. Alto costo de vida, sede de Amazon y otros gigantes tecnológicos. Entorno natural hermoso.",
  },
  38: {
    zh: "美国内陆增长最快城市，薪资不错。生活成本相对较低，户外活动资源丰富。创业成本低。",
    en: "The fastest-growing inland US city with good salaries. Relatively low cost of living and abundant outdoor recreation. Low startup costs.",
    ja: "米国内陸部で最も成長が速い都市で、給与も良好。生活費が比較的安く、アウトドア資源が豊富。起業コストが低い。",
    es: "La ciudad interior de más rápido crecimiento en EE.UU. con buenos salarios. Costo de vida relativamente bajo y abundantes actividades al aire libre. Bajo costo para emprender.",
  },
  39: {
    zh: "美国增长最快的科技中心之一，薪资上升。生活成本相对低，文化活动丰富。初创公司集中。",
    en: "One of the fastest-growing US tech hubs with rising salaries. Relatively low cost of living and vibrant cultural scene. Concentration of startups.",
    ja: "米国で最も成長が速いテックハブの一つで、給与も上昇中。生活費が比較的安く、文化活動が活発。スタートアップが集中。",
    es: "Uno de los centros tecnológicos de más rápido crecimiento en EE.UU. con salarios en alza. Costo de vida relativamente bajo y rica vida cultural. Concentración de startups.",
  },
  40: {
    zh: "加拿大宜居城市，薪资中等偏高。生活成本高，自然景观优美。亚洲贸易门户。",
    en: "A livable Canadian city with moderately high salaries. High cost of living and beautiful natural landscapes. Gateway for Asian trade.",
    ja: "住みやすいカナダの都市で、給与は中〜高水準。生活費は高いが、自然景観が美しい。アジア貿易の玄関口。",
    es: "Ciudad habitable de Canadá con salarios moderadamente altos. Alto costo de vida y hermosos paisajes naturales. Puerta de entrada al comercio asiático.",
  },
  41: {
    zh: "加拿大文化中心，薪资相对较低。生活成本低，法语文化特色。艺术和科技产业发展。",
    en: "Canada's cultural center with relatively low salaries. Low cost of living and distinctive French-speaking culture. Growing arts and tech industries.",
    ja: "カナダの文化の中心地で、給与はやや低め。生活費が安く、フランス語文化が特色。アートとテック産業が発展中。",
    es: "Centro cultural de Canadá con salarios relativamente bajos. Bajo costo de vida y cultura francófona distintiva. Industrias artísticas y tecnológicas en desarrollo.",
  },
  42: {
    zh: "澳大利亚文化之都，薪资竞争力强。生活成本较高，多元文化和创意产业发达。宜居度高。",
    en: "Australia's cultural capital with competitive salaries. Relatively high cost of living, thriving multicultural and creative industries. Highly livable.",
    ja: "オーストラリアの文化の都で、給与競争力が高い。生活費はやや高いが、多文化・クリエイティブ産業が盛ん。住みやすさ抜群。",
    es: "Capital cultural de Australia con salarios competitivos. Costo de vida relativamente alto, con industrias multiculturales y creativas desarrolladas. Alta habitabilidad.",
  },
  43: {
    zh: "澳大利亚增长最快城市，薪资不错。生活成本相对低，气候温暖。房地产市场活跃。",
    en: "Australia's fastest-growing city with good salaries. Relatively low cost of living and warm climate. Active real estate market.",
    ja: "オーストラリアで最も成長が速い都市で、給与も良好。生活費が比較的安く、気候が温暖。不動産市場が活発。",
    es: "La ciudad de más rápido crecimiento en Australia con buenos salarios. Costo de vida relativamente bajo y clima cálido. Mercado inmobiliario activo.",
  },
  44: {
    zh: "新西兰最大城市，薪资中等偏高。生活成本相对高，自然环境优美。南太平洋门户。",
    en: "New Zealand's largest city with moderately high salaries. Relatively high cost of living and beautiful natural environment. Gateway to the South Pacific.",
    ja: "ニュージーランド最大の都市で、給与は中〜高水準。生活費はやや高いが、自然環境が美しい。南太平洋の玄関口。",
    es: "La ciudad más grande de Nueva Zelanda con salarios moderadamente altos. Costo de vida relativamente alto y hermoso entorno natural. Puerta de entrada al Pacífico Sur.",
  },
  45: {
    zh: "东南亚商业门户，薪资较低。生活成本极低，美食文化著名。数字游民天堂。",
    en: "Southeast Asia's commercial gateway with low salaries. Extremely low cost of living and world-famous food culture. A digital nomad paradise.",
    ja: "東南アジアの商業の玄関口で、給与は低め。生活費が極めて安く、食文化で有名。デジタルノマドの楽園。",
    es: "Puerta de entrada comercial del sudeste asiático con salarios bajos. Costo de vida extremadamente bajo y famosa cultura gastronómica. Paraíso para nómadas digitales.",
  },
  46: {
    zh: "马来西亚经济中心，薪资相对较低。生活成本低，多元化城市。投资和创业成本低。",
    en: "Malaysia's economic center with relatively low salaries. Low cost of living and a multicultural city. Low investment and startup costs.",
    ja: "マレーシアの経済の中心地で、給与はやや低め。生活費が安く、多文化都市。投資・起業コストが低い。",
    es: "Centro económico de Malasia con salarios relativamente bajos. Bajo costo de vida y ciudad multicultural. Bajos costos de inversión y emprendimiento.",
  },
  47: {
    zh: "越南最大商业城市，薪资较低。生活成本极低，发展势头强劲。数字游民费用最低。",
    en: "Vietnam's largest commercial city with low salaries. Extremely low cost of living and strong growth momentum. Among the lowest costs for digital nomads.",
    ja: "ベトナム最大の商業都市で、給与は低め。生活費が極めて安く、成長の勢いが強い。デジタルノマドの費用は最安水準。",
    es: "La mayor ciudad comercial de Vietnam con salarios bajos. Costo de vida extremadamente bajo y fuerte impulso de crecimiento. De los costos más bajos para nómadas digitales.",
  },
  48: {
    zh: "越南首都，薪资水平低。生活成本极低，千年文化底蕴。创业生态快速发展。",
    en: "Vietnam's capital with low salaries. Extremely low cost of living and a thousand years of cultural heritage. Rapidly developing startup ecosystem.",
    ja: "ベトナムの首都で、給与水準は低め。生活費が極めて安く、千年の文化的蓄積がある。スタートアップのエコシステムが急成長中。",
    es: "Capital de Vietnam con salarios bajos. Costo de vida extremadamente bajo y mil años de herencia cultural. Ecosistema emprendedor en rápido desarrollo.",
  },
  49: {
    zh: "印度IT产业中心，薪资增长快。生活成本极低，全球IT人才聚集地。创新生态活跃。",
    en: "India's IT industry hub with fast-growing salaries. Extremely low cost of living and a global gathering point for IT talent. Vibrant innovation ecosystem.",
    ja: "インドのIT産業の中心地で、給与の伸びが速い。生活費が極めて安く、世界中のIT人材が集まる。イノベーションのエコシステムが活発。",
    es: "Centro de la industria IT de India con salarios en rápido crecimiento. Costo de vida extremadamente bajo y punto de encuentro global de talento IT. Ecosistema de innovación activo.",
  },
  50: {
    zh: "印度金融中心，薪资在印度最高。生活成本低，商业和娱乐产业发达。贫富差距较大。",
    en: "India's financial center with the highest salaries in India. Low cost of living, thriving business and entertainment industries. Significant wealth inequality.",
    ja: "インドの金融の中心地で、国内最高水準の給与。生活費は安いが、ビジネスとエンタメ産業が盛ん。貧富の差が大きい。",
    es: "Centro financiero de India con los salarios más altos del país. Bajo costo de vida, con industrias comerciales y de entretenimiento desarrolladas. Notable desigualdad económica.",
  },
  51: {
    zh: "印度政治中心，薪资相对较低。生活成本极低，政府机构雇主众多。污染问题需关注。",
    en: "India's political center with relatively low salaries. Extremely low cost of living and many government employers. Pollution is a concern.",
    ja: "インドの政治の中心地で、給与はやや低め。生活費が極めて安く、政府機関の雇用が多い。大気汚染に注意が必要。",
    es: "Centro político de India con salarios relativamente bajos. Costo de vida extremadamente bajo y numerosos empleadores gubernamentales. La contaminación es una preocupación.",
  },
  52: {
    zh: "东非经济中心，薪资相对较低。生活成本低，科技创业平台发展迅速。非洲硅谷地位上升。",
    en: "East Africa's economic center with relatively low salaries. Low cost of living and a rapidly growing tech startup scene. Rising status as Africa's Silicon Valley.",
    ja: "東アフリカの経済の中心地で、給与はやや低め。生活費が安く、テックスタートアップが急成長中。アフリカのシリコンバレーとしての地位が上昇。",
    es: "Centro económico de África Oriental con salarios relativamente bajos. Bajo costo de vida y escena de startups tecnológicas en rápido crecimiento. Creciente estatus como el Silicon Valley de África.",
  },
  53: {
    zh: "中东北非最大城市，薪资较低。生活成本极低，古老文明与现代融合。人口密集。",
    en: "The largest city in the Middle East and North Africa with low salaries. Extremely low cost of living, blending ancient civilization with modernity. Densely populated.",
    ja: "中東・北アフリカ最大の都市で、給与は低め。生活費が極めて安く、古代文明と現代が融合。人口密度が高い。",
    es: "La ciudad más grande de Medio Oriente y Norte de África con salarios bajos. Costo de vida extremadamente bajo, fusión de civilización antigua y modernidad. Altamente poblada.",
  },
  54: {
    zh: "伊朗政治经济中心，薪资相对较低。生活成本极低，教育资源丰富。政治风险需考虑。",
    en: "Iran's political and economic center with relatively low salaries. Extremely low cost of living and abundant educational resources. Political risk should be considered.",
    ja: "イランの政治・経済の中心地で、給与はやや低め。生活費が極めて安く、教育資源が豊富。政治リスクの考慮が必要。",
    es: "Centro político y económico de Irán con salarios relativamente bajos. Costo de vida extremadamente bajo y abundantes recursos educativos. El riesgo político debe considerarse.",
  },
  55: {
    zh: "巴基斯坦最大城市，薪资较低。生活成本极低，商业活动活跃。安全形势需关注。",
    en: "Pakistan's largest city with low salaries. Extremely low cost of living and active commercial activity. Security situation requires attention.",
    ja: "パキスタン最大の都市で、給与は低め。生活費が極めて安く、商業活動が活発。治安状況に注意が必要。",
    es: "La ciudad más grande de Pakistán con salarios bajos. Costo de vida extremadamente bajo y actividad comercial activa. La situación de seguridad requiere atención.",
  },
  56: {
    zh: "巴基斯坦首都，薪资相对较低。生活成本极低，城市规划现代化。政治敏感城市。",
    en: "Pakistan's capital with relatively low salaries. Extremely low cost of living and modern urban planning. A politically sensitive city.",
    ja: "パキスタンの首都で、給与はやや低め。生活費が極めて安く、都市計画が近代的。政治的にデリケートな都市。",
    es: "Capital de Pakistán con salarios relativamente bajos. Costo de vida extremadamente bajo y planificación urbana moderna. Ciudad políticamente sensible.",
  },
  57: {
    zh: "印度尼西亚最大城市，薪资相对较低。生活成本低，东南亚重要经济中心。交通堵塞问题。",
    en: "Indonesia's largest city with relatively low salaries. Low cost of living and a major Southeast Asian economic center. Traffic congestion is a concern.",
    ja: "インドネシア最大の都市で、給与はやや低め。生活費が安く、東南アジアの重要な経済の中心地。交通渋滞が課題。",
    es: "La ciudad más grande de Indonesia con salarios relativamente bajos. Bajo costo de vida y un importante centro económico del sudeste asiático. El tráfico es un problema.",
  },
  58: {
    zh: "菲律宾最大城市，薪资较低。生活成本极低，BPO产业发达。快速发展的经济体。",
    en: "The Philippines' largest city with low salaries. Extremely low cost of living and a thriving BPO industry. A rapidly growing economy.",
    ja: "フィリピン最大の都市で、給与は低め。生活費が極めて安く、BPO産業が盛ん。急成長中の経済。",
    es: "La ciudad más grande de Filipinas con salarios bajos. Costo de vida extremadamente bajo e industria BPO desarrollada. Economía en rápido crecimiento.",
  },
  59: {
    zh: "韩国首都，薪资水平不错。生活成本相对日本低，科技和文化产业发达。竞争压力大。",
    en: "South Korea's capital with good salaries. Lower cost of living compared to Japan, with thriving tech and cultural industries. Highly competitive environment.",
    ja: "韓国の首都で、給与水準は良好。生活費は日本より比較的安く、テックと文化産業が盛ん。競争のプレッシャーが大きい。",
    es: "Capital de Corea del Sur con buenos salarios. Costo de vida relativamente menor que Japón, con industrias tecnológicas y culturales desarrolladas. Alta presión competitiva.",
  },
  60: {
    zh: "韩国第二大城市，薪资相对较低。生活成本低，海港贸易中心。生活节奏相对悠闲。",
    en: "South Korea's second-largest city with relatively low salaries. Low cost of living and a major port trade center. A relatively relaxed pace of life.",
    ja: "韓国第二の都市で、給与はやや低め。生活費が安く、港湾貿易の中心地。生活のペースは比較的ゆったり。",
    es: "La segunda ciudad más grande de Corea del Sur con salarios relativamente bajos. Bajo costo de vida y centro de comercio portuario. Ritmo de vida relativamente relajado.",
  },
  61: {
    zh: "台湾政治经济中心，薪资中等。生活成本相对低，电子产业全球领先。民主社会。",
    en: "Taiwan's political and economic center with moderate salaries. Relatively low cost of living and a world leader in electronics. A democratic society.",
    ja: "台湾の政治・経済の中心地で、給与は中程度。生活費が比較的安く、電子産業で世界をリード。民主主義社会。",
    es: "Centro político y económico de Taiwán con salarios moderados. Costo de vida relativamente bajo y líder mundial en electrónica. Sociedad democrática.",
  },
  62: {
    zh: "南美最欧洲化的城市，薪资相对较低。生活成本中等偏低，文化底蕴深厚。金融中心地位。",
    en: "South America's most Europeanized city with relatively low salaries. Moderately low cost of living and deep cultural heritage. A regional financial center.",
    ja: "南米で最もヨーロッパ的な都市で、給与はやや低め。生活費は中〜低水準で、文化的な蓄積が深い。金融センターとしての地位。",
    es: "La ciudad más europeizada de Sudamérica con salarios relativamente bajos. Costo de vida moderadamente bajo y profunda herencia cultural. Centro financiero regional.",
  },
  63: {
    zh: "智利经济中心，薪资中等。生活成本相对低，矿业和葡萄酒文化众所周知。政治稳定。",
    en: "Chile's economic center with moderate salaries. Relatively low cost of living, known for mining and wine culture. Politically stable.",
    ja: "チリの経済の中心地で、給与は中程度。生活費が比較的安く、鉱業とワイン文化で知られる。政治的に安定。",
    es: "Centro económico de Chile con salarios moderados. Costo de vida relativamente bajo, conocido por la minería y la cultura del vino. Políticamente estable.",
  },
  64: {
    zh: "哥伦比亚首都，薪资相对较低。生活成本低，海拔高气候宜人。咖啡产业著名。",
    en: "Colombia's capital with relatively low salaries. Low cost of living, high altitude with pleasant climate. Famous for its coffee industry.",
    ja: "コロンビアの首都で、給与はやや低め。生活費が安く、高地で気候が快適。コーヒー産業で有名。",
    es: "Capital de Colombia con salarios relativamente bajos. Bajo costo de vida, altitud elevada con clima agradable. Famosa por su industria cafetera.",
  },
  65: {
    zh: "秘鲁首都，薪资较低。生活成本低，印加文化遗产世界知名。矿产资源丰富。",
    en: "Peru's capital with low salaries. Low cost of living and world-renowned Inca cultural heritage. Rich mineral resources.",
    ja: "ペルーの首都で、給与は低め。生活費が安く、インカ文化遺産が世界的に有名。鉱物資源が豊富。",
    es: "Capital de Perú con salarios bajos. Bajo costo de vida y patrimonio cultural inca de renombre mundial. Abundantes recursos minerales.",
  },
  67: {
    zh: "南非经济中心，薪资相对较低。生活成本低，金融和采矿业主导。安全问题需关注。",
    en: "South Africa's economic center with relatively low salaries. Low cost of living, dominated by finance and mining. Security concerns require attention.",
    ja: "南アフリカの経済の中心地で、給与はやや低め。生活費が安く、金融・鉱業が主導。治安面の注意が必要。",
    es: "Centro económico de Sudáfrica con salarios relativamente bajos. Bajo costo de vida, dominado por finanzas y minería. La seguridad requiere atención.",
  },
  68: {
    zh: "南非最宜居城市，薪资较低。生活成本低，自然景观和旅游业发达。创意产业活跃。",
    en: "South Africa's most livable city with low salaries. Low cost of living, thriving natural scenery and tourism. Active creative industries.",
    ja: "南アフリカで最も住みやすい都市で、給与は低め。生活費が安く、自然景観と観光業が盛ん。クリエイティブ産業が活発。",
    es: "La ciudad más habitable de Sudáfrica con salarios bajos. Bajo costo de vida, con paisajes naturales y turismo desarrollados. Industrias creativas activas.",
  },
  69: {
    zh: "墨西哥第二大城市，薪资相对较低。生活成本低，教育和医疗资源丰富。生活成本上升。",
    en: "Mexico's second-largest city with relatively low salaries. Low cost of living and abundant education and healthcare resources. Rising cost of living.",
    ja: "メキシコ第二の都市で、給与はやや低め。生活費が安く、教育・医療資源が豊富。生活費は上昇傾向。",
    es: "La segunda ciudad más grande de México con salarios relativamente bajos. Bajo costo de vida y abundantes recursos educativos y médicos. Costo de vida en aumento.",
  },
  70: {
    zh: "哥斯达黎加首都，薪资相对较低。生活成本低，医疗质量高。退休和数字游民目的地。",
    en: "Costa Rica's capital with relatively low salaries. Low cost of living and high-quality healthcare. A destination for retirees and digital nomads.",
    ja: "コスタリカの首都で、給与はやや低め。生活費が安く、医療の質が高い。退職者やデジタルノマドの目的地。",
    es: "Capital de Costa Rica con salarios relativamente bajos. Bajo costo de vida y atención médica de alta calidad. Destino para jubilados y nómadas digitales.",
  },
  71: {
    zh: "巴拿马经济中心，薪资中等。生活成本相对低，运河贸易枢纽。美元计价的稳定。",
    en: "Panama's economic center with moderate salaries. Relatively low cost of living; a canal trade hub. Stability backed by USD denomination.",
    ja: "パナマの経済中心地、給与は中程度。生活費は比較的低く、運河貿易のハブ。米ドル建ての安定性。",
    es: "Centro económico de Panamá con salarios moderados. Costo de vida relativamente bajo; hub comercial del canal. Estabilidad respaldada por el dólar.",
  },
  73: {
    zh: "美国海外领土，薪资中等。生活成本相对高，美国基础设施和福利。税收优惠吸引人才。",
    en: "U.S. overseas territory with moderate salaries. Relatively high cost of living; U.S. infrastructure and benefits. Tax incentives attract talent.",
    ja: "米国海外領土、給与は中程度。生活費はやや高いが、米国のインフラと福利厚生あり。税制優遇が人材を引きつける。",
    es: "Territorio estadounidense con salarios moderados. Costo de vida relativamente alto; infraestructura y beneficios de EE.UU. Incentivos fiscales atraen talento.",
  },
  75: {
    zh: "阿联酋首都，薪资竞争力强。生活成本相对低，石油富国。国际企业总部众多。",
    en: "Capital of the UAE with competitive salaries. Relatively low cost of living; an oil-rich nation. Home to many international corporate headquarters.",
    ja: "UAE の首都、給与の競争力が高い。生活費は比較的低く、石油富国。国際企業の本社が多数集積。",
    es: "Capital de los EAU con salarios competitivos. Costo de vida relativamente bajo; nación rica en petróleo. Numerosas sedes de empresas internacionales.",
  },
  76: {
    zh: "卡塔尔首都，薪资水平高。生活成本相对低，石油国家。国际事件主办国。",
    en: "Capital of Qatar with high salary levels. Relatively low cost of living; an oil-rich state. Host of major international events.",
    ja: "カタールの首都、給与水準が高い。生活費は比較的低く、石油国家。国際的な大型イベントの開催地。",
    es: "Capital de Catar con salarios altos. Costo de vida relativamente bajo; estado petrolero. País anfitrión de eventos internacionales.",
  },
  77: {
    zh: "巴林经济中心，薪资中等。生活成本低，海湾地区金融中心。石油和金融驱动。",
    en: "Bahrain's economic center with moderate salaries. Low cost of living; a Gulf region financial hub. Driven by oil and finance.",
    ja: "バーレーンの経済中心地、給与は中程度。生活費が低く、湾岸地域の金融ハブ。石油と金融が経済を牽引。",
    es: "Centro económico de Baréin con salarios moderados. Bajo costo de vida; centro financiero del Golfo. Impulsado por petróleo y finanzas.",
  },
  78: {
    zh: "沙特首都，薪资相对较低。生活成本低，石油经济支撑。快速现代化和多元化。",
    en: "Capital of Saudi Arabia with relatively low salaries. Low cost of living; supported by an oil economy. Rapidly modernizing and diversifying.",
    ja: "サウジアラビアの首都、給与はやや低め。生活費が低く、石油経済が支える。急速な近代化と多角化が進行中。",
    es: "Capital de Arabia Saudita con salarios relativamente bajos. Bajo costo de vida; economía respaldada por el petróleo. Rápida modernización y diversificación.",
  },
  79: {
    zh: "阿曼首都，薪资相对较低。生活成本低，中东最稳定的国家之一。旅游和贸易发达。",
    en: "Capital of Oman with relatively low salaries. Low cost of living; one of the most stable countries in the Middle East. Thriving tourism and trade.",
    ja: "オマーンの首都、給与はやや低め。生活費が低く、中東で最も安定した国の一つ。観光と貿易が盛ん。",
    es: "Capital de Omán con salarios relativamente bajos. Bajo costo de vida; uno de los países más estables de Oriente Medio. Turismo y comercio prósperos.",
  },
  80: {
    zh: "黎巴嫩经济中心，薪资相对较低。生活成本相对高，中东文化枢纽。政治形势复杂。",
    en: "Lebanon's economic center with relatively low salaries. Relatively high cost of living; a cultural hub of the Middle East. Complex political situation.",
    ja: "レバノンの経済中心地、給与はやや低め。生活費は比較的高く、中東の文化拠点。政治情勢は複雑。",
    es: "Centro económico de Líbano con salarios relativamente bajos. Costo de vida relativamente alto; centro cultural de Oriente Medio. Situación política compleja.",
  },
  81: {
    zh: "约旦首都，薪资相对较低。生活成本低，历史遗址丰富。中东政治之枢。",
    en: "Capital of Jordan with relatively low salaries. Low cost of living; rich in historical sites. A political pivot of the Middle East.",
    ja: "ヨルダンの首都、給与はやや低め。生活費が低く、歴史遺跡が豊富。中東政治の要衝。",
    es: "Capital de Jordania con salarios relativamente bajos. Bajo costo de vida; rica en sitios históricos. Eje político de Oriente Medio.",
  },
  82: {
    zh: "以色列经济中心和高科技中心，薪资竞争力强。生活成本高，创新和创业闻名。",
    en: "Israel's economic and high-tech center with competitive salaries. High cost of living; renowned for innovation and entrepreneurship.",
    ja: "イスラエルの経済・ハイテク中心地、給与の競争力が高い。生活費は高いが、イノベーションと起業で世界的に有名。",
    es: "Centro económico y tecnológico de Israel con salarios competitivos. Alto costo de vida; reconocida por su innovación y emprendimiento.",
  },
  83: {
    zh: "印度新兴IT中心，薪资相对较低。生活成本极低，快速发展潜力大。成本优势明显。",
    en: "An emerging IT hub in India with relatively low salaries. Extremely low cost of living; strong growth potential. Clear cost advantage.",
    ja: "インドの新興 IT 拠点、給与はやや低め。生活費が極めて低く、急成長の潜在力あり。コスト優位性が際立つ。",
    es: "Centro emergente de TI en India con salarios relativamente bajos. Costo de vida extremadamente bajo; gran potencial de crecimiento. Clara ventaja en costos.",
  },
  84: {
    zh: "印度教育和IT中心，薪资相对低。生活成本非常低，气候宜人。创业成本最低。",
    en: "India's education and IT center with relatively low salaries. Very low cost of living; pleasant climate. Among the lowest startup costs.",
    ja: "インドの教育・IT 拠点、給与はやや低め。生活費が非常に低く、気候が快適。起業コストが最も低い都市の一つ。",
    es: "Centro educativo y de TI de India con salarios relativamente bajos. Costo de vida muy bajo; clima agradable. Costos de emprendimiento mínimos.",
  },
  85: {
    zh: "乌克兰首都，薪资相对较低。生活成本低，IT人才集中。政治形势存在风险。",
    en: "Capital of Ukraine with relatively low salaries. Low cost of living; concentrated IT talent. Political situation carries risks.",
    ja: "ウクライナの首都、給与はやや低め。生活費が低く、IT 人材が集中。政治的リスクが存在する。",
    es: "Capital de Ucrania con salarios relativamente bajos. Bajo costo de vida; concentración de talento en TI. La situación política conlleva riesgos.",
  },
  86: {
    zh: "罗马尼亚首都，薪资相对较低。生活成本低，IT外包中心。欧洲增长潜力城市。",
    en: "Capital of Romania with relatively low salaries. Low cost of living; an IT outsourcing center. A European city with strong growth potential.",
    ja: "ルーマニアの首都、給与はやや低め。生活費が低く、IT アウトソーシングの中心地。欧州で成長ポテンシャルの高い都市。",
    es: "Capital de Rumanía con salarios relativamente bajos. Bajo costo de vida; centro de outsourcing de TI. Ciudad europea con gran potencial de crecimiento.",
  },
  87: {
    zh: "保加利亚首都，薪资相对低。生活成本极低，欧盟最便宜城市之一。创业成本低。",
    en: "Capital of Bulgaria with relatively low salaries. Extremely low cost of living; one of the cheapest EU cities. Low startup costs.",
    ja: "ブルガリアの首都、給与はやや低め。生活費が極めて低く、EU 内で最も物価の安い都市の一つ。起業コストが低い。",
    es: "Capital de Bulgaria con salarios relativamente bajos. Costo de vida extremadamente bajo; una de las ciudades más baratas de la UE. Bajos costos de emprendimiento.",
  },
  88: {
    zh: "克罗地亚首都，薪资中等。生活成本低，亚得里亚海沿岸。旅游和IT产业发达。",
    en: "Capital of Croatia with moderate salaries. Low cost of living; along the Adriatic coast. Thriving tourism and IT industries.",
    ja: "クロアチアの首都、給与は中程度。生活費が低く、アドリア海沿岸に位置。観光と IT 産業が盛ん。",
    es: "Capital de Croacia con salarios moderados. Bajo costo de vida; junto a la costa adriática. Industrias de turismo y TI prósperas.",
  },
  89: {
    zh: "塞尔维亚首都，薪资相对低。生活成本低，夜生活氛围浓厚。数字游民和创业热点。",
    en: "Capital of Serbia with relatively low salaries. Low cost of living; vibrant nightlife scene. A hotspot for digital nomads and startups.",
    ja: "セルビアの首都、給与はやや低め。生活費が低く、ナイトライフが活発。デジタルノマドとスタートアップのホットスポット。",
    es: "Capital de Serbia con salarios relativamente bajos. Bajo costo de vida; vibrante vida nocturna. Punto caliente para nómadas digitales y startups.",
  },
  90: {
    zh: "匈牙利首都，薪资相对较低。生活成本低，温泉和文化闻名。欧洲宜居城市。",
    en: "Capital of Hungary with relatively low salaries. Low cost of living; famous for thermal baths and culture. A livable European city.",
    ja: "ハンガリーの首都、給与はやや低め。生活費が低く、温泉と文化で有名。ヨーロッパで住みやすい都市。",
    es: "Capital de Hungría con salarios relativamente bajos. Bajo costo de vida; famosa por sus termas y cultura. Una ciudad europea habitable.",
  },
  91: {
    zh: "斯洛伐克首都，薪资相对较低。生活成本低，多瑙河明珠。IT和制造业发达。",
    en: "Capital of Slovakia with relatively low salaries. Low cost of living; a Danube gem. Thriving IT and manufacturing sectors.",
    ja: "スロバキアの首都、給与はやや低め。生活費が低く、ドナウ川の宝石。IT と製造業が盛ん。",
    es: "Capital de Eslovaquia con salarios relativamente bajos. Bajo costo de vida; joya del Danubio. Sectores de TI y manufactura prósperos.",
  },
  92: {
    zh: "斯洛文尼亚首都，薪资中等。生活成本相对低，绿色首都。欧盟高质量生活。",
    en: "Capital of Slovenia with moderate salaries. Relatively low cost of living; a green capital. High quality of life within the EU.",
    ja: "スロベニアの首都、給与は中程度。生活費は比較的低く、グリーン首都。EU 内で高い生活の質。",
    es: "Capital de Eslovenia con salarios moderados. Costo de vida relativamente bajo; capital verde. Alta calidad de vida dentro de la UE.",
  },
  93: {
    zh: "爱尔兰经济中心，薪资竞争力强。生活成本高，科技企业总部集中。英语国家优势。",
    en: "Ireland's economic center with competitive salaries. High cost of living; a concentration of tech company headquarters. English-speaking country advantage.",
    ja: "アイルランドの経済中心地、給与の競争力が高い。生活費は高いが、テック企業の本社が集中。英語圏の強み。",
    es: "Centro económico de Irlanda con salarios competitivos. Alto costo de vida; concentración de sedes de empresas tech. Ventaja de país anglófono.",
  },
  94: {
    zh: "北爱经济中心，薪资相对较低。生活成本普遍较低，创意产业和金融发展。英镑计价。",
    en: "Northern Ireland's economic center with relatively low salaries. Generally low cost of living; growing creative and financial sectors. GBP-denominated.",
    ja: "北アイルランドの経済中心地、給与はやや低め。生活費は全般的に低く、クリエイティブ産業と金融が発展。英ポンド建て。",
    es: "Centro económico de Irlanda del Norte con salarios relativamente bajos. Costo de vida generalmente bajo; industrias creativas y financieras en crecimiento. Denominado en libras.",
  },
  95: {
    zh: "美国东南部中心，薪资水平中等。生活成本相对低，商业和物流枢纽。增长潜力大。",
    en: "A center of the U.S. Southeast with moderate salaries. Relatively low cost of living; a business and logistics hub. Strong growth potential.",
    ja: "米国南東部の中心都市、給与は中程度。生活費は比較的低く、ビジネスと物流のハブ。成長ポテンシャルが高い。",
    es: "Centro del sureste de EE.UU. con salarios moderados. Costo de vida relativamente bajo; hub de negocios y logística. Gran potencial de crecimiento.",
  },
  96: {
    zh: "美国西南部中心，薪资相对较低。生活成本低，气候干燥。发展和房地产活跃。",
    en: "A center of the U.S. Southwest with relatively low salaries. Low cost of living; dry climate. Active development and real estate market.",
    ja: "米国南西部の中心都市、給与はやや低め。生活費が低く、乾燥した気候。開発と不動産市場が活発。",
    es: "Centro del suroeste de EE.UU. con salarios relativamente bajos. Bajo costo de vida; clima seco. Mercado inmobiliario y desarrollo activos.",
  },
  97: {
    zh: "美国太平洋西北部中心，薪资中等。生活成本中等，气候宜人。创业和技术产业。",
    en: "A center of the U.S. Pacific Northwest with moderate salaries. Moderate cost of living; pleasant climate. Startup and tech industries.",
    ja: "米国太平洋岸北西部の中心都市、給与は中程度。生活費は中程度で気候が快適。スタートアップとテック産業が盛ん。",
    es: "Centro del noroeste del Pacífico de EE.UU. con salarios moderados. Costo de vida moderado; clima agradable. Industrias de startups y tecnología.",
  },
  98: {
    zh: "美国西海岸城市，薪资中等偏高。生活成本高，气候全年宜人。军事和生物技术产业。",
    en: "A U.S. West Coast city with moderately high salaries. High cost of living; year-round pleasant climate. Military and biotech industries.",
    ja: "米国西海岸の都市、給与は中〜高水準。生活費は高いが、年間を通じて気候が快適。軍事とバイオテック産業。",
    es: "Ciudad de la costa oeste de EE.UU. con salarios medio-altos. Alto costo de vida; clima agradable todo el año. Industrias militar y biotecnológica.",
  },
  99: {
    zh: "美国娱乐中心，薪资相对较低。生活成本低，旅游和服务业发达。房地产市场活跃。",
    en: "America's entertainment capital with relatively low salaries. Low cost of living; thriving tourism and service industries. Active real estate market.",
    ja: "米国のエンターテインメントの中心地、給与はやや低め。生活費が低く、観光とサービス業が盛ん。不動産市場が活発。",
    es: "Capital del entretenimiento de EE.UU. con salarios relativamente bajos. Bajo costo de vida; turismo y servicios prósperos. Mercado inmobiliario activo.",
  },
  100: {
    zh: "美国佛罗里达州中心，薪资相对较低。生活成本低，气候温暖。医疗和物流产业发达。",
    en: "A center of Florida, USA with relatively low salaries. Low cost of living; warm climate. Thriving healthcare and logistics industries.",
    ja: "米国フロリダ州の中心都市、給与はやや低め。生活費が低く、温暖な気候。医療と物流産業が発達。",
    es: "Centro de Florida, EE.UU. con salarios relativamente bajos. Bajo costo de vida; clima cálido. Industrias de salud y logística prósperas.",
  },
  101: {
    zh: "中国南方经济重镇，珠三角核心城市。制造业和贸易发达，美食文化丰富。气候炎热潮湿。",
    en: "A major economic hub in southern China; a core Pearl River Delta city. Thriving manufacturing and trade; rich culinary culture. Hot and humid climate.",
    ja: "中国南部の経済重鎮、珠江デルタの中核都市。製造業と貿易が盛んで、食文化が豊か。高温多湿な気候。",
    es: "Importante centro económico del sur de China; ciudad clave del delta del río Perla. Manufactura y comercio prósperos; rica cultura gastronómica. Clima cálido y húmedo.",
  },
  102: {
    zh: "中国科技创新之都，腾讯、华为等巨头总部所在地。年轻、活力四射的现代化城市。",
    en: "China's tech innovation capital; headquarters of giants like Tencent and Huawei. A young, vibrant, and modern city.",
    ja: "中国のテックイノベーションの都、Tencent や Huawei など巨大企業の本社所在地。若くて活気あふれる近代都市。",
    es: "Capital de innovación tecnológica de China; sede de gigantes como Tencent y Huawei. Una ciudad joven, vibrante y moderna.",
  },
  103: {
    zh: "中国西南中心城市，以美食和休闲文化闻名。新兴科技中心，生活成本相对较低。",
    en: "A central city in southwest China, famous for its cuisine and laid-back culture. An emerging tech hub with relatively low cost of living.",
    ja: "中国南西部の中心都市、美食とのんびりした文化で有名。新興テックハブで生活費が比較的低い。",
    es: "Ciudad central del suroeste de China, famosa por su gastronomía y cultura relajada. Centro tech emergente con costo de vida relativamente bajo.",
  },
  104: {
    zh: "阿里巴巴总部所在地，中国电商与互联网产业重镇。西湖闻名世界，宜居城市。",
    en: "Headquarters of Alibaba; a major hub for China's e-commerce and internet industries. World-famous West Lake; a livable city.",
    ja: "Alibaba の本社所在地、中国の EC・インターネット産業の重要拠点。西湖が世界的に有名な住みやすい都市。",
    es: "Sede de Alibaba; centro de la industria de comercio electrónico e internet de China. Famosa mundialmente por el Lago del Oeste; ciudad habitable.",
  },
  105: {
    zh: "中国西南最大直辖市，山城地形独特。制造业和物流中心，生活成本较低，美食丰富。",
    en: "China's largest municipality in the southwest; unique mountainous terrain. A manufacturing and logistics hub with low cost of living and rich cuisine.",
    ja: "中国南西部最大の直轄市、山城ならではの独特な地形。製造業と物流の中心で、生活費が低く美食が豊富。",
    es: "El municipio más grande del suroeste de China; terreno montañoso único. Centro de manufactura y logística con bajo costo de vida y rica gastronomía.",
  },
  106: {
    zh: "日本第二大都市圈，商业与美食之都。生活成本低于东京，文化独特热情奔放。",
    en: "Japan's second-largest metro area; a capital of commerce and cuisine. Lower cost of living than Tokyo; a uniquely warm and lively culture.",
    ja: "日本第2の大都市圏、商業と食の都。生活費は東京より低く、独自の熱気あふれる文化が魅力。",
    es: "Segunda área metropolitana de Japón; capital del comercio y la gastronomía. Costo de vida menor que Tokio; cultura cálida y vibrante.",
  },
  107: {
    zh: "日本中部工业重镇，丰田汽车总部所在地。生活成本适中，制造业就业机会丰富。",
    en: "A major industrial city in central Japan; headquarters of Toyota. Moderate cost of living; abundant manufacturing job opportunities.",
    ja: "日本中部の工業重鎮、トヨタ自動車の本社所在地。生活費は適度で、製造業の雇用機会が豊富。",
    es: "Importante ciudad industrial del centro de Japón; sede de Toyota. Costo de vida moderado; abundantes oportunidades de empleo en manufactura.",
  },
  109: {
    zh: "柬埔寨首都，东南亚新兴经济体。房地产和旅游业增长迅速，生活成本极低。",
    en: "Capital of Cambodia; an emerging Southeast Asian economy. Rapid growth in real estate and tourism; extremely low cost of living.",
    ja: "カンボジアの首都、東南アジアの新興経済国。不動産と観光業が急成長中で、生活費が極めて低い。",
    es: "Capital de Camboya; economía emergente del sudeste asiático. Rápido crecimiento inmobiliario y turístico; costo de vida extremadamente bajo.",
  },
  110: {
    zh: "缅甸最大城市和经济中心。历史建筑丰富，生活成本极低但基础设施有待发展。",
    en: "Myanmar's largest city and economic center. Rich in historic architecture; extremely low cost of living but infrastructure needs development.",
    ja: "ミャンマー最大の都市で経済の中心地。歴史的建築が豊富で生活費は極めて低いが、インフラ整備が課題。",
    es: "La ciudad más grande y centro económico de Myanmar. Rica en arquitectura histórica; costo de vida extremadamente bajo, pero infraestructura en desarrollo.",
  },
  112: {
    zh: "泰国北部文化中心，数字游民圣地。生活成本低廉，气候宜人，寺庙文化丰富。",
    en: "A cultural center in northern Thailand; a digital nomad haven. Low cost of living; pleasant climate and rich temple culture.",
    ja: "タイ北部の文化拠点、デジタルノマドの聖地。生活費が安く、気候が快適で寺院文化が豊か。",
    es: "Centro cultural del norte de Tailandia; refugio de nómadas digitales. Bajo costo de vida; clima agradable y rica cultura de templos.",
  },
  114: {
    zh: "孟加拉国首都，全球人口最密集城市之一。服装制造业中心，生活成本极低但空气质量差。",
    en: "Capital of Bangladesh; one of the world's most densely populated cities. A garment manufacturing center; extremely low cost of living but poor air quality.",
    ja: "バングラデシュの首都、世界で最も人口密度の高い都市の一つ。衣料品製造の中心地で生活費は極めて低いが、大気質が悪い。",
    es: "Capital de Bangladés; una de las ciudades más densamente pobladas del mundo. Centro de manufactura textil; costo de vida extremadamente bajo, pero mala calidad del aire.",
  },
  115: {
    zh: "斯里兰卡商业首都，印度洋贸易枢纽。旅游和IT服务业增长，生活成本较低。",
    en: "Sri Lanka's commercial capital; an Indian Ocean trade hub. Growing tourism and IT services; relatively low cost of living.",
    ja: "スリランカの商業首都、インド洋の貿易ハブ。観光と IT サービスが成長中で、生活費は比較的低い。",
    es: "Capital comercial de Sri Lanka; hub comercial del océano Índico. Turismo y servicios de TI en crecimiento; costo de vida relativamente bajo.",
  },
  116: {
    zh: "尼泊尔首都，喜马拉雅山脚下的古城。旅游业为主，生活成本极低但空气质量季节性差。",
    en: "Capital of Nepal; an ancient city at the foot of the Himalayas. Tourism-driven economy; extremely low cost of living but seasonal air quality issues.",
    ja: "ネパールの首都、ヒマラヤ山麓の古都。観光業が主産業で生活費は極めて低いが、季節的に大気質が悪化。",
    es: "Capital de Nepal; ciudad antigua al pie del Himalaya. Economía basada en turismo; costo de vida extremadamente bajo, pero calidad del aire estacional.",
  },
  117: {
    zh: "哈萨克斯坦最大城市和经济中心。前首都，天山脚下，IT和金融业发展迅速。",
    en: "Kazakhstan's largest city and economic center. Former capital at the foot of the Tian Shan mountains; rapidly growing IT and finance sectors.",
    ja: "カザフスタン最大の都市で経済中心地。天山山脈のふもとの旧首都、IT と金融が急速に発展中。",
    es: "La ciudad más grande y centro económico de Kazajistán. Antigua capital al pie de las montañas Tian Shan; sectores de TI y finanzas en rápido crecimiento.",
  },
  118: {
    zh: "乌兹别克斯坦首都，中亚最大城市。丝绸之路历史名城，经济改革中快速发展。",
    en: "Capital of Uzbekistan; the largest city in Central Asia. A historic Silk Road city; rapidly developing amid economic reforms.",
    ja: "ウズベキスタンの首都、中央アジア最大の都市。シルクロードの歴史都市で、経済改革のもと急速に発展中。",
    es: "Capital de Uzbekistán; la ciudad más grande de Asia Central. Ciudad histórica de la Ruta de la Seda; desarrollo rápido en medio de reformas económicas.",
  },
  119: {
    zh: "阿塞拜疆首都，里海沿岸石油之城。现代化建筑与古城并存，能源经济为主。",
    en: "Capital of Azerbaijan; an oil city on the Caspian coast. Modern architecture coexists with the old city; energy-driven economy.",
    ja: "アゼルバイジャンの首都、カスピ海沿岸の石油都市。近代建築と旧市街が共存し、エネルギー経済が中心。",
    es: "Capital de Azerbaiyán; ciudad petrolera en la costa del Caspio. Arquitectura moderna coexiste con la ciudad antigua; economía basada en energía.",
  },
  120: {
    zh: "蒙古首都，全球最寒冷首都之一。采矿业驱动经济，冬季空气污染严重。",
    en: "Capital of Mongolia; one of the coldest capitals in the world. Mining-driven economy; severe air pollution in winter.",
    ja: "モンゴルの首都、世界で最も寒い首都の一つ。鉱業が経済を牽引するが、冬季の大気汚染が深刻。",
    es: "Capital de Mongolia; una de las capitales más frías del mundo. Economía impulsada por la minería; grave contaminación del aire en invierno.",
  },
  121: {
    zh: "瑞典首都，北欧最大经济体。高福利体系、领先的科技创新生态（Spotify、Klarna）。生活成本较高但公共服务完善。",
    en: "Capital of Sweden, the largest Nordic economy. Strong welfare system and leading tech innovation ecosystem (Spotify, Klarna). High cost of living but excellent public services.",
    ja: "スウェーデンの首都、北欧最大の経済圏。手厚い福祉制度と先進的なテックエコシステム（Spotify、Klarna）。生活費は高いが公共サービスが充実。",
    es: "Capital de Suecia, la mayor economía nórdica. Sólido sistema de bienestar y ecosistema tecnológico líder (Spotify, Klarna). Alto costo de vida pero excelentes servicios públicos.",
  },
  122: {
    zh: "丹麦首都，全球最宜居城市之一。绿色能源先驱、自行车友好城市。薪资水平高，税率也高。",
    en: "Capital of Denmark, one of the world's most livable cities. Green energy pioneer and bike-friendly city. High salaries but also high tax rates.",
    ja: "デンマークの首都、世界で最も住みやすい都市のひとつ。グリーンエネルギーの先駆者で自転車に優しい街。給与水準は高いが税率も高い。",
    es: "Capital de Dinamarca, una de las ciudades más habitables del mundo. Pionera en energía verde y ciudad amigable con la bicicleta. Salarios altos, pero también impuestos elevados.",
  },
  123: {
    zh: "芬兰首都，全球教育标杆。清洁能源、桑拿文化。科技创新活跃（Nokia、游戏产业）。冬季漫长但城市基建完善。",
    en: "Capital of Finland, a global benchmark in education. Clean energy and sauna culture. Active tech innovation scene (Nokia, gaming industry). Long winters but well-developed urban infrastructure.",
    ja: "フィンランドの首都、世界の教育モデル。クリーンエネルギーとサウナ文化。テックイノベーションが活発（Nokia、ゲーム産業）。冬は長いが都市インフラが充実。",
    es: "Capital de Finlandia, referente mundial en educación. Energía limpia y cultura de sauna. Innovación tecnológica activa (Nokia, industria de videojuegos). Inviernos largos pero infraestructura urbana completa.",
  },
  124: {
    zh: "挪威首都，全球收入最高的城市之一。石油基金支撑的高福利体系。生活成本极高，自然环境优美。",
    en: "Capital of Norway, one of the highest-income cities in the world. A robust welfare system backed by the sovereign oil fund. Extremely high cost of living with beautiful natural surroundings.",
    ja: "ノルウェーの首都、世界有数の高所得都市。石油基金に支えられた手厚い福祉制度。生活費は極めて高いが自然環境に恵まれている。",
    es: "Capital de Noruega, una de las ciudades con mayores ingresos del mundo. Sólido sistema de bienestar respaldado por el fondo petrolero soberano. Costo de vida extremadamente alto con un entorno natural hermoso.",
  },
  125: {
    zh: "美国第四大城市，全球能源之都。NASA 约翰逊航天中心所在地。生活成本低于沿海大城市，无州所得税。",
    en: "Fourth-largest U.S. city and global energy capital. Home to NASA's Johnson Space Center. Lower cost of living than coastal metros, with no state income tax.",
    ja: "全米第4の都市、世界のエネルギー首都。NASAジョンソン宇宙センターの所在地。沿岸部の大都市より生活費が安く、州所得税がない。",
    es: "Cuarta ciudad más grande de EE.UU. y capital mundial de la energía. Sede del Centro Espacial Johnson de la NASA. Costo de vida más bajo que las grandes ciudades costeras, sin impuesto estatal sobre la renta.",
  },
  126: {
    zh: "美国第六大城市，美国独立诞生地。医疗教育资源丰富（宾大、杰斐逊医院）。生活成本低于纽约但高于中西部。",
    en: "Sixth-largest U.S. city, birthplace of American independence. Rich in medical and educational resources (UPenn, Jefferson Hospital). Lower cost of living than New York but higher than the Midwest.",
    ja: "全米第6の都市、アメリカ独立発祥の地。医療・教育資源が豊富（ペンシルベニア大学、ジェファーソン病院）。生活費はニューヨークより安いが中西部より高い。",
    es: "Sexta ciudad más grande de EE.UU., cuna de la independencia estadounidense. Rica en recursos médicos y educativos (UPenn, Hospital Jefferson). Costo de vida menor que Nueva York pero mayor que el Medio Oeste.",
  },
  127: {
    zh: "加拿大能源之都，落基山脉门户。移民热门目的地，生活成本低于温哥华和多伦多。阿尔伯塔省无省销售税。",
    en: "Canada's energy capital and gateway to the Rocky Mountains. A popular immigration destination with lower cost of living than Vancouver and Toronto. Alberta has no provincial sales tax.",
    ja: "カナダのエネルギー首都、ロッキー山脈への玄関口。移民に人気の都市で、生活費はバンクーバーやトロントより安い。アルバータ州には州売上税がない。",
    es: "Capital energética de Canadá y puerta a las Montañas Rocosas. Destino popular de inmigración con costo de vida menor que Vancouver y Toronto. Alberta no tiene impuesto provincial sobre ventas.",
  },
  128: {
    zh: "澳大利亚西海岸唯一大城市，矿业经济支柱。阳光充沛，生活节奏轻松。远离其他主要城市但自然环境优越。",
    en: "The only major city on Australia's west coast, anchored by the mining economy. Abundant sunshine and a relaxed pace of life. Remote from other major cities but with an outstanding natural environment.",
    ja: "オーストラリア西海岸唯一の大都市、鉱業経済が支柱。日照豊かでゆったりとした生活リズム。他の主要都市からは遠いが自然環境は抜群。",
    es: "Única gran ciudad de la costa oeste de Australia, sostenida por la economía minera. Abundante sol y ritmo de vida relajado. Lejos de otras ciudades principales pero con un entorno natural excepcional.",
  },
  129: {
    zh: "哥伦比亚第二大城市，全球数字游民热门目的地。春城气候（年均22°C）。科技创新生态快速发展，生活成本极低。",
    en: "Colombia's second-largest city and a top global destination for digital nomads. Spring-like climate year-round (avg. 22°C). A fast-growing tech innovation ecosystem with very low cost of living.",
    ja: "コロンビア第2の都市、世界的に人気のデジタルノマド目的地。年間平均22°Cの常春の気候。テックエコシステムが急成長中で、生活費は極めて低い。",
    es: "Segunda ciudad más grande de Colombia y destino top mundial para nómadas digitales. Clima primaveral todo el año (promedio 22°C). Ecosistema tecnológico en rápido crecimiento con costo de vida muy bajo.",
  },
  130: {
    zh: "格鲁吉亚首都，数字游民新兴目的地。极低生活成本、美食红酒文化。一年免签政策吸引全球远程工作者。",
    en: "Capital of Georgia, an emerging destination for digital nomads. Extremely low cost of living with rich food and wine culture. A one-year visa-free policy attracts remote workers worldwide.",
    ja: "ジョージアの首都、デジタルノマドの新興目的地。生活費が極めて低く、美食とワインの文化が豊か。1年間のビザなし滞在が世界中のリモートワーカーを引きつけている。",
    es: "Capital de Georgia, destino emergente para nómadas digitales. Costo de vida extremadamente bajo con rica cultura gastronómica y vinícola. La política de un año sin visa atrae a trabajadores remotos de todo el mundo.",
  },
  131: {
    zh: "尼日利亚最大城市，非洲第一大经济体商业中心。人口超2000万。科技创业生态蓬勃（\"Silicon Lagoon\"）。基建和安全是主要挑战。",
    en: "Nigeria's largest city and commercial hub of Africa's biggest economy. Population exceeds 20 million. A booming tech startup ecosystem (\"Silicon Lagoon\"). Infrastructure and safety remain key challenges.",
    ja: "ナイジェリア最大の都市、アフリカ第1の経済大国の商業中心地。人口は2000万超。テックスタートアップが活況（\"Silicon Lagoon\"）。インフラと治安が主要課題。",
    es: "La ciudad más grande de Nigeria y centro comercial de la mayor economía de África. Población superior a 20 millones. Ecosistema de startups tecnológicas en auge (\"Silicon Lagoon\"). Infraestructura y seguridad son los principales desafíos.",
  },
  132: {
    zh: "俄罗斯首都，全球 GDP 前20城市。2022年后受制裁影响，部分国际数据来源受限。科技和金融中心，生活成本在制裁后大幅波动。",
    en: "Capital of Russia, a top-20 global GDP city. International data sources have been limited since 2022 sanctions. A tech and financial center where cost of living has fluctuated significantly post-sanctions.",
    ja: "ロシアの首都、世界GDP上位20都市。2022年以降の制裁により一部の国際データソースが制限されている。テック・金融の中心地で、制裁後は生活費が大きく変動。",
    es: "Capital de Rusia, entre las 20 ciudades con mayor PIB del mundo. Desde las sanciones de 2022, algunas fuentes de datos internacionales están limitadas. Centro tecnológico y financiero con costos de vida que han fluctuado significativamente tras las sanciones.",
  },
  133: {
    zh: "美国硅谷核心城市，全球科技产业中心。苹果、Alphabet等巨头总部所在地。薪资极高，房价和生活成本也为全美最高之列。",
    en: "Core city of Silicon Valley and the global tech industry hub. Home to Apple, Alphabet, and other tech giants. Extremely high salaries, but housing and cost of living rank among the highest in the U.S.",
    ja: "シリコンバレーの中核都市、世界のテック産業の中心地。Apple、Alphabetなど大手テック企業の本社が集結。給与は極めて高いが、住宅費と生活費も全米トップクラス。",
    es: "Ciudad central de Silicon Valley y epicentro de la industria tecnológica mundial. Sede de Apple, Alphabet y otros gigantes tecnológicos. Salarios extremadamente altos, pero el precio de vivienda y costo de vida están entre los más altos de EE.UU.",
  },
  135: {
    zh: "加拿大首都，联邦政府所在地。科技产业发达（\"Silicon Valley North\"）。双语城市（英法语），生活成本低于多伦多。",
    en: "Capital of Canada and seat of the federal government. A thriving tech sector (\"Silicon Valley North\"). A bilingual city (English/French) with lower cost of living than Toronto.",
    ja: "カナダの首都、連邦政府の所在地。テック産業が盛ん（\"Silicon Valley North\"）。英仏バイリンガル都市で、生活費はトロントより低い。",
    es: "Capital de Canadá y sede del gobierno federal. Sector tecnológico próspero (\"Silicon Valley North\"). Ciudad bilingüe (inglés/francés) con costo de vida menor que Toronto.",
  },
  136: {
    zh: "卢森堡首都，欧盟机构所在地。全球人均 GDP 最高国家。基金管理中心，多语言国际化环境。城市规模小但极度富裕。",
    en: "Capital of Luxembourg and home to EU institutions. The country with the highest GDP per capita in the world. A fund management hub with a multilingual, international environment. Small in size but extremely wealthy.",
    ja: "ルクセンブルクの首都、EU機関の所在地。世界で最も一人当たりGDPが高い国。ファンド運用の中心地で多言語・国際的な環境。都市規模は小さいが極めて裕福。",
    es: "Capital de Luxemburgo y sede de instituciones de la UE. El país con el PIB per cápita más alto del mundo. Centro de gestión de fondos con un entorno multilingüe e internacional. Ciudad pequeña pero extremadamente próspera.",
  },
  137: {
    zh: "爱沙尼亚首都，全球数字化程度最高的国家。电子公民、在线投票先驱。科技创业活跃（Skype 诞生地），生活成本低于西欧。",
    en: "Capital of Estonia, the most digitally advanced country in the world. Pioneer of e-residency and online voting. An active tech startup scene (birthplace of Skype) with lower cost of living than Western Europe.",
    ja: "エストニアの首都、世界で最もデジタル化が進んだ国。電子市民権やオンライン投票の先駆者。テックスタートアップが活発（Skype発祥の地）で、生活費は西欧より低い。",
    es: "Capital de Estonia, el país más digitalizado del mundo. Pionero en e-residencia y voto en línea. Escena activa de startups tecnológicas (cuna de Skype) con costo de vida menor que Europa Occidental.",
  },
  138: {
    zh: "日本九州最大城市，连续多年被评为日本最宜居城市。美食之都（博多拉面）。初创企业支援政策领先，生活成本远低于东京。",
    en: "The largest city in Kyushu, Japan, consistently rated as Japan's most livable city. A food capital (Hakata ramen). Leading startup support policies with a cost of living far below Tokyo.",
    ja: "九州最大の都市、日本で最も住みやすい都市に選ばれ続けている。グルメの街（博多ラーメン）。スタートアップ支援が先進的で、生活費は東京を大きく下回る。",
    es: "La ciudad más grande de Kyushu, Japón, calificada constantemente como la más habitable de Japón. Capital gastronómica (ramen de Hakata). Políticas de apoyo a startups líderes con costo de vida muy inferior al de Tokio.",
  },
  140: {
    zh: "印度尼西亚最著名的旅游岛屿，也是全球数字游民第一目的地。仓古（Canggu）和乌布（Ubud）拥有大量共享办公空间、瑜伽馆和冲浪点。生活成本低廉，文化体验丰富，但基础设施和网络较雅加达薄弱。",
    en: "Indonesia's most famous tourist island and the world's top digital nomad destination. Canggu and Ubud offer abundant coworking spaces, yoga studios, and surf spots. Very low cost of living with rich cultural experiences, though infrastructure and internet lag behind Jakarta.",
    ja: "インドネシアで最も有名な観光島であり、世界一のデジタルノマド目的地。チャングーとウブドにはコワーキングスペース、ヨガスタジオ、サーフスポットが豊富。生活費が安く文化体験も豊かだが、インフラやネット環境はジャカルタに劣る。",
    es: "La isla turística más famosa de Indonesia y el destino número uno del mundo para nómadas digitales. Canggu y Ubud cuentan con abundantes espacios de coworking, estudios de yoga y puntos de surf. Costo de vida muy bajo con ricas experiencias culturales, aunque la infraestructura e internet son inferiores a Yakarta.",
  },
  141: {
    zh: "越南中部海滨城市，以美溪海滩、低廉生活成本和快速增长的游民社区闻名。拥有良好的光纤网络和现代化基础设施，是nomads.com全球排名第二的数字游民城市。",
    en: "A coastal city in central Vietnam, known for My Khe Beach, low cost of living, and a fast-growing nomad community. Solid fiber internet and modern infrastructure make it the #2 digital nomad city on nomads.com.",
    ja: "ベトナム中部の海辺の街、ミーケービーチ・低コスト生活・急成長するノマドコミュニティで知られる。光ファイバー網と近代的インフラが整い、nomads.comで世界第2位のデジタルノマド都市。",
    es: "Ciudad costera del centro de Vietnam, conocida por la playa My Khe, su bajo costo de vida y una comunidad nómada en rápido crecimiento. Buena red de fibra óptica e infraestructura moderna; es la segunda ciudad para nómadas digitales en nomads.com.",
  },
  143: {
    zh: "葡萄牙第二大城市，以波特酒、杜罗河谷和色彩斑斓的老城闻名。近年成为欧洲数字游民热门目的地，拥有优质光纤网络、丰富的共享办公空间，生活成本低于里斯本。",
    en: "Portugal's second-largest city, famed for port wine, the Douro Valley, and its colorful old town. It has become a popular European digital nomad hub with excellent fiber internet, ample coworking spaces, and a lower cost of living than Lisbon.",
    ja: "ポルトガル第2の都市、ポートワイン・ドウロ渓谷・色鮮やかな旧市街で知られる。近年ヨーロッパのデジタルノマドに人気で、高品質な光回線・豊富なコワーキングスペースがあり、生活費はリスボンより安い。",
    es: "Segunda ciudad más grande de Portugal, famosa por el vino de Oporto, el Valle del Duero y su colorido casco antiguo. Se ha convertido en un destino popular para nómadas digitales en Europa, con excelente fibra óptica, abundantes espacios de coworking y un costo de vida menor que Lisboa.",
  },
  144: {
    zh: "西班牙第三大城市，地中海气候温暖宜人，拥有发达的科技创业生态和大量共享办公空间。生活成本低于巴塞罗那和马德里，是nomads.com欧洲排名前10的游民城市。",
    en: "Spain's third-largest city with a warm Mediterranean climate, a thriving tech startup ecosystem, and numerous coworking spaces. Lower cost of living than Barcelona and Madrid; ranked in the top 10 European nomad cities on nomads.com.",
    ja: "スペイン第3の都市、温暖な地中海性気候に恵まれ、テックスタートアップのエコシステムとコワーキングスペースが充実。生活費はバルセロナやマドリードより安く、nomads.comの欧州トップ10ノマド都市に選出。",
    es: "Tercera ciudad más grande de España, con un cálido clima mediterráneo, un próspero ecosistema de startups tecnológicas y numerosos espacios de coworking. Costo de vida menor que Barcelona y Madrid; entre las 10 principales ciudades europeas para nómadas en nomads.com.",
  },
  146: {
    zh: "克罗地亚第二大城市，达尔马提亚海岸明珠。戴克里先宫和亚得里亚海的壮丽景色吸引了大量游民定居。克罗地亚提供专门的数字游民签证，免缴当地所得税。",
    en: "Croatia's second-largest city, a gem on the Dalmatian coast. Diocletian's Palace and stunning Adriatic views attract many nomads to settle here. Croatia offers a dedicated digital nomad visa with no local income tax.",
    ja: "クロアチア第2の都市、ダルマチア海岸の宝石。ディオクレティアヌス宮殿とアドリア海の絶景が多くのノマドを惹きつけている。クロアチアは専用のデジタルノマドビザを提供し、現地所得税が免除される。",
    es: "Segunda ciudad más grande de Croacia, joya de la costa dálmata. El Palacio de Diocleciano y las impresionantes vistas del Adriático atraen a muchos nómadas. Croacia ofrece una visa específica para nómadas digitales sin impuesto local sobre la renta.",
  },
  147: {
    zh: "泰国最大岛屿，以海滩、夜生活和旅游基础设施闻名。拥有国际机场和大量共享办公空间，是海滩型数字游民的热门选择。持Thailand DTV签证可合法长期居留。",
    en: "Thailand's largest island, known for its beaches, nightlife, and tourist infrastructure. With an international airport and abundant coworking spaces, it's a popular choice for beach-loving digital nomads. The Thailand DTV visa allows legal long-term stays.",
    ja: "タイ最大の島、ビーチ・ナイトライフ・観光インフラで知られる。国際空港とコワーキングスペースが充実し、ビーチ派デジタルノマドに人気。Thailand DTVビザで合法的に長期滞在が可能。",
    es: "La isla más grande de Tailandia, conocida por sus playas, vida nocturna e infraestructura turística. Con aeropuerto internacional y abundantes espacios de coworking, es una opción popular para nómadas digitales amantes de la playa. La visa DTV de Tailandia permite estadías legales a largo plazo.",
  },
  148: {
    zh: "乌拉圭首都，南美洲最稳定、最安全的国家之一。拥有优质的公共医疗体系和较高的民主指数。生活节奏悠闲，牛排和红酒文化浓厚。对远程工作者有良好的税收政策。",
    en: "Capital of Uruguay, one of the most stable and safest countries in South America. Excellent public healthcare and a high democracy index. A relaxed pace of life with a rich steak and wine culture. Favorable tax policies for remote workers.",
    ja: "ウルグアイの首都、南米で最も安定し安全な国のひとつ。優れた公的医療制度と高い民主主義指数。ゆったりとした生活リズムに、ステーキとワインの文化が根づく。リモートワーカー向けの税制優遇あり。",
    es: "Capital de Uruguay, uno de los países más estables y seguros de Sudamérica. Excelente sistema de salud pública y alto índice democrático. Ritmo de vida relajado con una fuerte cultura de carne y vino. Políticas fiscales favorables para trabajadores remotos.",
  },
  149: {
    zh: "西班牙加纳利群岛最大城市，全年春天般的气候使其成为欧洲数字游民的'老牌'目的地。拥有成熟的共享办公生态、优质的光纤网络和大量直飞航线。作为欧盟领土，无需额外签证。",
    en: "The largest city in Spain's Canary Islands, with year-round spring-like weather that makes it a classic European digital nomad destination. A mature coworking ecosystem, quality fiber internet, and numerous direct flights. As EU territory, no extra visa is required.",
    ja: "スペイン・カナリア諸島最大の都市、年間を通じて春のような気候でヨーロッパのデジタルノマドの「定番」目的地。成熟したコワーキング環境・高品質な光回線・豊富な直行便が揃う。EU領土のため追加ビザ不要。",
    es: "La ciudad más grande de las Islas Canarias de España, con clima primaveral todo el año que la convierte en un destino clásico para nómadas digitales europeos. Ecosistema maduro de coworking, fibra óptica de calidad y numerosos vuelos directos. Como territorio de la UE, no se requiere visa adicional.",
  },
  150: {
    zh: "马来西亚北部岛屿州，乔治市是联合国教科文组织世界遗产城市。以街头美食、低廉生活成本和多元文化著称。英语普及率高，是东南亚性价比最高的数字游民目的地之一。",
    en: "A northern Malaysian island state; George Town is a UNESCO World Heritage city. Renowned for street food, low cost of living, and multiculturalism. High English proficiency makes it one of the best-value digital nomad destinations in Southeast Asia.",
    ja: "マレーシア北部の島州、ジョージタウンはユネスコ世界遺産都市。ストリートフード・低い生活費・多文化で知られる。英語普及率が高く、東南アジアで最もコスパの良いデジタルノマド目的地のひとつ。",
    es: "Estado insular del norte de Malasia; George Town es ciudad Patrimonio de la Humanidad por la UNESCO. Famosa por su comida callejera, bajo costo de vida y multiculturalismo. Alto nivel de inglés, es uno de los destinos con mejor relación calidad-precio para nómadas digitales en el Sudeste Asiático.",
  },
  152: {
    zh: "巴西南部'魔力岛'，南美科技创业中心之一。拥有42个海滩、优质的生活质量和蓬勃发展的本土科技生态。是巴西最适合数字游民的城市，生活成本低于圣保罗和里约。",
    en: "The 'Magic Island' in southern Brazil, one of South America's tech startup hubs. With 42 beaches, high quality of life, and a thriving local tech ecosystem, it's Brazil's best city for digital nomads — at a lower cost than São Paulo or Rio.",
    ja: "ブラジル南部の「魔法の島」、南米有数のテックスタートアップ拠点。42のビーチ、高い生活の質、活気ある地元テックエコシステムを持ち、ブラジルで最もデジタルノマドに適した都市。生活費はサンパウロやリオより安い。",
    es: "La 'Isla Mágica' del sur de Brasil, uno de los centros de startups tecnológicas de Sudamérica. Con 42 playas, alta calidad de vida y un próspero ecosistema tecnológico local, es la mejor ciudad de Brasil para nómadas digitales, con costos menores que São Paulo o Río.",
  },
  159: {
    zh: "日本千年古都，拥有17处UNESCO世界遗产和超过2000座寺庙神社。四季分明的文化风情，春樱秋叶尤为动人。生活节奏比东京大阪更为从容，大学城学术氛围浓厚。",
    en: "Japan's ancient capital for a millennium, home to 17 UNESCO World Heritage Sites and over 2,000 temples and shrines. Distinct four-season charm — especially stunning during cherry blossom and autumn foliage. A more relaxed pace than Tokyo or Osaka, with a strong university-town academic atmosphere.",
    ja: "日本の千年の古都、17のユネスコ世界遺産と2000以上の寺社を擁する。四季折々の風情が魅力で、特に春の桜と秋の紅葉は格別。東京や大阪より穏やかな暮らしのリズムで、大学の街ならではの学術的雰囲気が漂う。",
    es: "Antigua capital de Japón durante un milenio, con 17 sitios del Patrimonio Mundial de la UNESCO y más de 2.000 templos y santuarios. Encanto distintivo en las cuatro estaciones, especialmente durante los cerezos en flor y el follaje otoñal. Un ritmo más relajado que Tokio u Osaka, con una fuerte atmósfera académica universitaria.",
  },
  160: {
    zh: "摩洛哥最大城市和经济首都，北非商业中心。地中海气候宜人，生活成本低廉。传统麦地那与现代金融城交融。",
    en: "Morocco's largest city and economic capital, the commercial hub of North Africa. Pleasant Mediterranean climate and low cost of living. A blend of traditional medina and modern financial district.",
    ja: "モロッコ最大の都市にして経済の中心地、北アフリカの商業ハブ。地中海性の穏やかな気候と低い生活費。伝統的なメディナと近代的な金融街が融合している。",
    es: "La ciudad más grande de Marruecos y su capital económica, centro comercial del norte de África. Agradable clima mediterráneo y bajo costo de vida. Fusión entre la medina tradicional y el distrito financiero moderno.",
  },
  161: {
    zh: "新西兰首都，世界最南端主权国家首都。政府与文化中心，咖啡馆密度全球最高。多风但宜居。",
    en: "Capital of New Zealand, the southernmost sovereign-state capital in the world. A center of government and culture with the world's highest density of coffee shops. Windy but livable.",
    ja: "ニュージーランドの首都、世界最南端の主権国家の首都。政府と文化の中心地で、カフェ密度は世界一。風は強いが住みやすい。",
    es: "Capital de Nueva Zelanda, la capital de un Estado soberano más austral del mundo. Centro de gobierno y cultura con la mayor densidad de cafeterías del mundo. Ventosa pero habitable.",
  },
  162: {
    zh: "立陶宛首都，波罗的海地区科技创新中心。生活成本远低于西欧，拥有全球首个数字游民签证计划。",
    en: "Capital of Lithuania, a tech innovation hub in the Baltics. Cost of living far below Western Europe, with the world's first dedicated digital nomad visa program.",
    ja: "リトアニアの首都、バルト地域のテックイノベーション拠点。生活費は西欧を大きく下回り、世界初のデジタルノマドビザ制度を持つ。",
    es: "Capital de Lituania, centro de innovación tecnológica en el Báltico. Costo de vida muy inferior al de Europa Occidental, con el primer programa de visa para nómadas digitales del mundo.",
  },
  163: {
    zh: "拉脱维亚首都，波罗的海明珠。新艺术建筑闻名，IT外包产业发达，生活品质高而成本低。",
    en: "Capital of Latvia, the pearl of the Baltics. Famous for its Art Nouveau architecture, with a strong IT outsourcing industry. High quality of life at a low cost.",
    ja: "ラトビアの首都、バルトの真珠。アール・ヌーヴォー建築で知られ、ITアウトソーシング産業が盛ん。生活の質が高く、コストは低い。",
    es: "Capital de Letonia, la perla del Báltico. Famosa por su arquitectura Art Nouveau, con una sólida industria de outsourcing de TI. Alta calidad de vida a bajo costo.",
  },
  164: {
    zh: "塞浦路斯首都，欧盟成员国，地中海东部的金融和科技中心。12.5%企业税率吸引大量国际企业。",
    en: "Capital of Cyprus, an EU member state, and a financial and tech hub in the eastern Mediterranean. A 12.5% corporate tax rate attracts many international businesses.",
    ja: "キプロスの首都、EU加盟国で地中海東部の金融・テックハブ。12.5%の法人税率が多くの国際企業を引きつけている。",
    es: "Capital de Chipre, Estado miembro de la UE, y centro financiero y tecnológico del Mediterráneo oriental. Una tasa de impuesto corporativo del 12,5% atrae a numerosas empresas internacionales.",
  },
  165: {
    zh: "多米尼加共和国首都，加勒比海地区最大经济体的中心。拥有官方数字游民签证，近年成为远程工作者热门目的地。",
    en: "Capital of the Dominican Republic, the center of the Caribbean's largest economy. Offers an official digital nomad visa and has become a popular destination for remote workers in recent years.",
    ja: "ドミニカ共和国の首都、カリブ海地域最大の経済圏の中心地。公式のデジタルノマドビザを提供し、近年リモートワーカーに人気の目的地に成長。",
    es: "Capital de la República Dominicana, centro de la mayor economía del Caribe. Ofrece una visa oficial para nómadas digitales y se ha convertido en un destino popular para trabajadores remotos en los últimos años.",
  },
  166: {
    zh: "厄瓜多尔首都，海拔2850米的赤道城市。使用美元为法定货币，生活成本极低，近年成为数字游民和退休移居热门目的地。",
    en: "Capital of Ecuador, an equatorial city at 2,850 m elevation. Uses the U.S. dollar as legal tender with an extremely low cost of living. In recent years, it has become a popular destination for digital nomads and retirement relocation.",
    ja: "エクアドルの首都、標高2850mの赤道直下の都市。米ドルを法定通貨として使用し、生活費は極めて低い。近年、デジタルノマドやリタイア移住先として人気が高まっている。",
    es: "Capital de Ecuador, ciudad ecuatorial a 2.850 m de altitud. Usa el dólar estadounidense como moneda oficial con un costo de vida extremadamente bajo. En los últimos años se ha convertido en un destino popular para nómadas digitales y jubilados.",
  },
  167: {
    zh: "加纳首都，西非英语国家经济中心。科技创业生态活跃，被称为'非洲硅谷'之一，是西非最稳定的民主国家。",
    en: "Capital of Ghana, the economic hub of English-speaking West Africa. An active tech startup ecosystem, often called one of 'Africa's Silicon Valleys,' in the most stable democracy in West Africa.",
    ja: "ガーナの首都、英語圏西アフリカの経済中心地。テックスタートアップが活発で「アフリカのシリコンバレー」と称され、西アフリカで最も安定した民主主義国家。",
    es: "Capital de Ghana, centro económico del África Occidental anglófona. Ecosistema activo de startups tecnológicas, conocido como uno de los 'Silicon Valley de África,' en la democracia más estable de África Occidental.",
  },
  168: {
    zh: "埃塞俄比亚首都，非洲联盟总部所在地。海拔2400米，全年气候温和。非洲增长最快的经济体之一，人口超过500万。",
    en: "Capital of Ethiopia and headquarters of the African Union. At 2,400 m elevation, it enjoys mild weather year-round. One of Africa's fastest-growing economies with a population exceeding 5 million.",
    ja: "エチオピアの首都、アフリカ連合本部の所在地。標高2400mで年間を通じ温暖な気候。アフリカで最も急成長する経済のひとつで、人口は500万超。",
    es: "Capital de Etiopía y sede de la Unión Africana. A 2.400 m de altitud, disfruta de un clima templado todo el año. Una de las economías de más rápido crecimiento en África con una población superior a 5 millones.",
  }
};
